[package]
name="ext4"
version="0.0.0"
edition="2021"

[lib]
crate-type=[
	"cdylib",
]

[target.'cfg(target_arch="wasm32")'.dependencies.wasm-bindgen]
version="^0.2"

[target.'cfg(target_arch="wasm32")'.dependencies.js-sys]
version="^0.3"
