#![no_std]

#[cfg(test)]
mod tests;

use core::mem::MaybeUninit;

#[cfg(all(target_arch="wasm32",target_os="unknown"))]
use wasm_bindgen::prelude::*;

#[repr(C)]
pub struct SuperBlock{
	pub s_inodes_count:[u8;4],
	pub s_blocks_count_lo:[u8;4],
	pub s_r_blocks_count_lo:[u8;4],
	pub s_free_blocks_count_lo:[u8;4],
	pub s_free_inodes_count:[u8;4],
	pub s_first_data_block:[u8;4],
	pub s_log_block_size:[u8;4],
	pub s_log_cluster_size:[u8;4],
	pub s_blocks_per_group:[u8;4],
	pub s_clusters_per_group:[u8;4],
	pub s_inodes_per_group:[u8;4],
	pub s_mtime:[u8;4],
	pub s_wtime:[u8;4],
	pub s_mnt_count:[u8;2],
	pub s_max_mnt_count:[u8;2],
	pub s_magic:[u8;2],
	pub s_state:[u8;2],
	pub s_errors:[u8;2],
	pub s_minor_rev_level:[u8;2],
	pub s_lastcheck:[u8;4],
	pub s_checkinterval:[u8;4],
	pub s_creator_os:[u8;4],
	pub s_rev_level:[u8;4],
	pub s_def_resuid:[u8;2],
	pub s_def_resgid:[u8;2],
	pub s_first_ino:[u8;4],
	pub s_inode_size:[u8;2],
	pub s_block_group_nr:[u8;2],
	pub s_feature_compat:[u8;4],
	pub s_feature_incompat:[u8;4],
	pub s_feature_ro_compat:[u8;4],
	pub s_uuid:[u8;16],
	pub s_volume_name:[u8;16],
	pub s_last_mounted:[u8;64],
	pub s_algorithm_usage_bitmap:[u8;4],
	pub s_prealloc_blocks:[u8;1],
	pub s_prealloc_dir_blocks:[u8;1],
	pub s_reserved_gdt_blocks:[u8;2],
	pub s_journal_uuid:[u8;16],
	pub s_journal_inum:[u8;4],
	pub s_journal_dev:[u8;4],
	pub s_last_orphan:[u8;4],
	pub s_hash_seed:[[u8;4];4],
	pub s_def_hash_version:[u8;1],
	pub s_jnl_backup_type:[u8;1],
	pub s_desc_size:[u8;2],
	pub s_default_mount_opts:[u8;4],
	pub s_first_meta_bg:[u8;4],
	pub s_mkfs_time:[u8;4],
	pub s_jnl_blocks:[[u8;4];17],
	pub s_block_count_hi:[u8;4],
	pub s_r_blocks_count_hi:[u8;4],
	pub s_free_blocks_count_hi:[u8;4],
	pub s_min_extra_isize:[u8;2],
	pub s_want_extra_isize:[u8;2],
	pub s_flags:[u8;4],
	pub s_raid_stride:[u8;2],
	pub s_mmp_interval:[u8;2],
	pub s_mmp_block:[u8;8],
	pub s_raid_stripe_width:[u8;4],
	pub s_log_groups_per_flex:[u8;1],
	pub s_checksum_type:[u8;1],
	pub s_reserved_pad:[u8;2],
	pub s_kbytes_written:[u8;8],
	pub s_snapshot_inum:[u8;4],
	pub s_snapshot_id:[u8;4],
	pub s_snapshot_r_blocks_count:[u8;8],
	pub s_snapshot_line:[u8;4],
	pub s_error_count:[u8;4],
	pub s_first_error_time:[u8;4],
	pub s_first_error_ino:[u8;4],
	pub s_first_error_block:[u8;8],
	pub s_first_error_func:[u8;32],
	pub s_first_error_line:[u8;4],
	pub s_last_error_time:[u8;4],
	pub s_last_error_ino:[u8;4],
	pub s_last_error_line:[u8;4],
	pub s_last_error_block:[u8;8],
	pub s_last_error_func:[u8;32],
	pub s_mount_opts:[u8;64],
	pub s_usr_quota_inum:[u8;4],
	pub s_grp_quota_inum:[u8;4],
	pub s_overhead_blocks:[u8;4],
	pub s_backup_bgs:[[u8;4];2],
	pub s_encrypt_algos:[u8;4],
	pub s_encrypt_pw_salt:[u8;16],
	pub s_lpf_ino:[u8;4],
	pub s_prj_quota_inum:[u8;4],
	pub s_checksum_seed:[u8;4],
	pub s_wtime_hi:[u8;1],
	pub s_mtime_hi:[u8;1],
	pub s_mkfs_time_hi:[u8;1],
	pub s_lastcheck_hi:[u8;1],
	pub s_first_error_time_hi:[u8;1],
	pub s_last_error_time_hi:[u8;1],
	pub s_pad:[u8;2],
	pub s_encoding:[u8;2],
	pub s_encoding_flags:[u8;2],
	pub s_orphan_file_inum:[u8;4],
	pub s_reserved:[[u8;4];94],
	pub s_checksum:[u8;4],
}

#[repr(C)]
pub struct GroupDescriptor{
	pub bg_block_bitmap_lo:[u8;4],
	pub bg_inode_bitmap_lo:[u8;4],
	pub bg_inode_table_lo:[u8;4],
	pub bg_free_block_count_lo:[u8;2],
	pub bg_free_inode_count_lo:[u8;2],
	pub bg_used_dirs_count_lo:[u8;2],
	pub bg_flags:[u8;2],
	pub bg_exclude_bitmap_lo:[u8;4],
	pub bg_block_bitmap_csum_lo:[u8;2],
	pub bg_inode_bitmap_csum_lo:[u8;2],
	pub bg_itable_unused_lo:[u8;2],
	pub bg_checksum:[u8;2],
	pub bg_block_bitmap_hi:[u8;4],
	pub bg_inode_bitmap_hi:[u8;4],
	pub bg_inode_table_hi:[u8;4],
	pub bg_free_blocks_count_hi:[u8;2],
	pub bg_free_inodes_count_hi:[u8;2],
	pub bg_used_dirs_count_hi:[u8;2],
	pub bg_itable_unused_hi:[u8;2],
	pub bg_exclude_bitmap_hi:[u8;4],
	pub bg_block_bitmap_csum_hi:[u8;2],
	pub bg_inode_bitmap_csum_hi:[u8;2],
	pub bg_reserved:[u8;4],
}

#[repr(C)]
pub struct MultipleMountProtection{
	pub mmp_magic:[u8;4],
	pub mmp_seq:[u8;4],
	pub mmp_time:[u8;8],
	pub mmp_nodename:[u8;64],
	pub mmp_bdevname:[u8;32],
	pub mmp_chech_interval:[u8;2],
	pub mmp_pad1:[u8;2],
	pub mmp_pad2:[[u8;4];226],
	pub mmp_mmp_checksum:[u8;4],
}

#[repr(C)]
pub struct IndexNode{
	pub i_mdoe:[u8;2],
	pub i_uid:[u8;2],
	pub i_size_lo:[u8;4],
	pub i_atime:[u8;4],
	pub i_ctime:[u8;4],
	pub i_mtime:[u8;4],
	pub i_dtime:[u8;4],
	pub i_gid:[u8;2],
	pub i_links_count:[u8;2],
	pub i_blocks_lo:[u8;4],
	pub i_flags:[u8;4],
	pub i_osd1:[u8;4],
	pub i_block:[[u8;4];15],
	pub i_generation:[u8;4],
	pub i_file_acl_lo:[u8;4],
	pub i_size_high:[u8;4],
	pub i_obso_faddr:[u8;4],
	pub i_osd2:[u8;12],
	pub i_extra_isize:[u8;2],
	pub i_checksum_hi:[u8;2],
	pub i_ctime_extra:[u8;4],
	pub i_mtime_extra:[u8;4],
	pub i_atime_extra:[u8;4],
	pub i_crtime:[u8;4],
	pub i_crtime_extra:[u8;4],
	pub i_version_hi:[u8;4],
	pub i_projid:[u8;4],
}
